### ISSUE TITLE
/tcmp release does not work (1.19 support)

### ISSUE THREAD

**Issue by Erisfiregamer1** [JNNGL/TotalComputers#16]
>:(
[18:53:39 ERROR]: Could not pass event EntityDismountEvent to TotalComputers v0.10.0b
java.lang.NullPointerException: Cannot invoke "io.netty.channel.Channel.eventLoop()" because "channel" is null
        at com.jnngl.packet.PacketListener.removePlayer(PacketListener.java:79) ~[tcmp-arm.jar:?]
        at com.jnngl.totalcomputers.TotalComputers.forceStopCapture(TotalComputers.java:341) ~[tcmp-arm.jar:?]
        at com.jnngl.totalcomputers.TotalComputers.dismount(TotalComputers.java:392) ~[tcmp-arm.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor223.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:git-Paper-29]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:664) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.entity.Entity.removePassenger(Entity.java:2765) ~[paper-1.19.jar:git-Paper-29]
        at net.minecraft.world.entity.Entity.stopRiding(Entity.java:2666) ~[paper-1.19.jar:git-Paper-29]
        at net.minecraft.world.entity.LivingEntity.stopRiding(LivingEntity.java:3524) ~[?:?]
        at net.minecraft.world.entity.player.Player.stopRiding(Player.java:1183) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.stopRiding(ServerPlayer.java:1438) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.stopRiding(ServerPlayer.java:1433) ~[?:?]
        at net.minecraft.world.entity.player.Player.rideTick(Player.java:521) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickPassenger(ServerLevel.java:1195) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1165) ~[?:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:898) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:692) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.19.jar:git-Paper-29]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:672) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1551) ~[paper-1.19.jar:git-Paper-29]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.jar:git-Paper-29]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1414) ~[paper-1.19.jar:git-Paper-29]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1187) ~[paper-1.19.jar:git-Paper-29]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-29]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[18:53:52 INFO]: Erisfiregamer1 issued server command: /tcmp release
[18:53:52 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'tcmp' in plugin TotalComputers v0.10.0b
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:900) ~[paper-1.19.jar:git-Paper-29]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2376) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$18(ServerGamePacketListenerImpl.java:2147) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.jar:git-Paper-29]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1358) ~[paper-1.19.jar:git-Paper-29]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[paper-1.19.jar:git-Paper-29]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1335) ~[paper-1.19.jar:git-Paper-29]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1328) ~[paper-1.19.jar:git-Paper-29]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1306) ~[paper-1.19.jar:git-Paper-29]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[paper-1.19.jar:git-Paper-29]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-29]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "io.netty.channel.Channel.eventLoop()" because "channel" is null
        at com.jnngl.packet.PacketListener.removePlayer(PacketListener.java:79) ~[tcmp-arm.jar:?]
        at com.jnngl.totalcomputers.TotalComputers.forceStopCapture(TotalComputers.java:341) ~[tcmp-arm.jar:?]
        at com.jnngl.totalcomputers.TotalComputers.onCommand(TotalComputers.java:1147) ~[tcmp-arm.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        ... 17 more

**Comment by Erisfiregamer1** [comment]
Errors get spammed after this

**Comment by JNNGL** [comment]
plugin doesnt support 1.19 yet

**Comment by Erisfiregamer1** [comment]
Fuck.
Leaving open for when plugin adds 1.19 support
