### ISSUE TITLE
DoubleBuffer is back (along with more issues)

### ISSUE THREAD

**Issue by Erisfiregamer1** [JNNGL/TotalComputers#3]
[13:59:33 ERROR]: [TotalComputers] [STDERR] An error occurred in the OS/application. This did not affect the operation of the OS, but if something does not work properly, create an issue on GitHub. In other cases, this error can be ignored.
[13:59:33 ERROR]: [TotalComputers] [STDERR] Stack Trace:
[13:59:33 ERROR]: [TotalComputers] [STDERR] Critical Error -> Uncaught exception: Cannot invoke "java.lang.Throwable.printStackTrace()" because "prevException[0]" is null

Afterward, once I got ALL users on my server to delete computers, I again got the old DoubleBuffer error
I also got a lot of these errors:
[14:23:08 ERROR]: [TotalComputers] [STDERR] Failed to find file.
[14:23:08 ERROR]: [TotalComputers] [STDERR] Failed to access file..

**Comment by Erisfiregamer1** [comment]
New error:
[14:29:17 ERROR]: [TotalComputers] [STDERR] Failed to find file.
[14:29:17 WARN]: Nag author(s): '[JNNGL]' of 'TotalComputers' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
[14:29:17 ERROR]: [TotalComputers] [STDERR] Failed to load image.
[14:29:17 WARN]: Exception in thread "Thread-717" java.util.ConcurrentModificationException
[14:29:17 WARN]:        at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
[14:29:17 WARN]:        at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
[14:29:17 WARN]:        at totalcomputers-0.9.2b5.jar//com.jnngl.system.AppStore.render(AppStore.java:224)
[14:29:17 WARN]:        at totalcomputers-0.9.2b5.jar//com.jnngl.totalcomputers.system.desktop.WindowApplication.renderCanvas(WindowApplication.java:201)
[14:29:17 WARN]:        at totalcomputers-0.9.2b5.jar//com.jnngl.system.AppStore.lambda$updateList$4(AppStore.java:185)
[14:29:17 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Erisfiregamer1** [comment]
> [STDERR] Critical Error -> Uncaught exception: Cannot invoke "java.lang.Throwable.printStackTrace()" because "prevException[0]" is null

I'd like to note this error was SPAMMED until the computers were removed.

**Comment by Erisfiregamer1** [comment]
Fixed.
