### ISSUE TITLE
NES emulator throws a "no sound" error

### ISSUE THREAD

**Issue by Erisfiregamer1** [JNNGL/TotalComputers#9]
[18:20:23 ERROR]: [STDERR] [com.grapeshot.halfnes.ui.HeadlessUI] Unable to inintialize sound.
[18:20:23 ERROR]: [TotalComputers] [STDERR] An error occurred in the OS/application. This did not affect the operation of the OS, but if something does not work properly, create an issue on GitHub. In other cases, this error can be ignored.
[18:20:23 ERROR]: [TotalComputers] [STDERR] Stack Trace:
[18:20:23 WARN]: java.lang.NullPointerException: Cannot invoke "java.awt.image.BufferedImage.getWidth()" because the return value of "com.grapeshot.halfnes.ui.HeadlessUI.getLastFrame()" is null
[18:20:23 WARN]:        at com.jnngl.applications.nes.NESEmulator.render(NESEmulator.java:180)
[18:20:23 WARN]:        at totalcomputers-0.9.2b5.jar//com.jnngl.totalcomputers.system.desktop.WindowApplication.renderCanvas(WindowApplication.java:201)
[18:20:23 WARN]:        at com.jnngl.applications.nes.NESEmulator.update(NESEmulator.java:167)
[18:20:23 WARN]:        at totalcomputers-0.9.2b5.jar//com.jnngl.totalcomputers.system.desktop.WindowApplication.updateApplication(WindowApplication.java:206)
[18:20:23 WARN]:        at totalcomputers-0.9.2b5.jar//com.jnngl.totalcomputers.system.states.Desktop.update(Desktop.java:212)
[18:20:23 WARN]:        at totalcomputers-0.9.2b5.jar//com.jnngl.totalcomputers.system.states.StateManager.update(StateManager.java:58)
[18:20:23 WARN]:        at totalcomputers-0.9.2b5.jar//com.jnngl.totalcomputers.system.TotalOS.renderFrame(TotalOS.java:195)
[18:20:23 WARN]:        at totalcomputers-0.9.2b5.jar//com.jnngl.totalcomputers.TotalComputers.lambda$initComputer$3(TotalComputers.java:1694)
[18:20:23 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[18:20:23 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[18:20:23 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[18:20:23 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[18:20:23 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[18:20:23 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

Possibly a side effect of bad natives.

**Comment by Erisfiregamer1** [comment]
Fixed! :D
